# Generated by Django 6.0.6 on 2026-06-30 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('status', models.CharField(choices=[('common', 'Общий конкурс'), ('target', 'Целевое'), ('special', 'Особая квота'), ('no_exam', 'Без вступительных'), ('unknown', 'Неизвестно')], default='common', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='parsers.program')),
            ],
            options={
                'ordering': ['program', 'position'],
                'unique_together': {('program', 'position')},
            },
        ),
    ]
