# Generated by Django 6.0.6 on 2026-06-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
