# Generated by Django 6.0.6 on 2026-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0003_program_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
