# Generated by Django 6.0.6 on 2026-07-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_alter_applicant_position'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='program',
            name='budget_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='university',
            name='short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
