# Generated by Django 6.0.6 on 2026-06-30 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Ваши баллы')),
                ('status', models.CharField(choices=[('common', 'Общий конкурс'), ('target', 'Целевое'), ('special', 'Особая квота'), ('no_exam', 'Без вступительных')], default='common', max_length=20, verbose_name='Ваш статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
